Description: |
  Downloads the latest version of Docker and creates a package, then
  uploads the package to Jamf Pro.

  Use the ARCHITECTURE and DOWNLOAD_TYPE keys to determine whether the
  Intel (amd64) or Apple Silicon (arm64) version of Docker for Mac is
  downloaded and packaged. Defaults to Intel if not overridden.
  Intel: "--key ARCHITECTURE=x86_64 --key DOWNLOAD_TYPE=amd64"
  Apple Silicon: "--key ARCHITECTURE=arm64 --key DOWNLOAD_TYPE=arm64"

  JSS_URL, API_USERNAME, and API_PASSWORD, and for non-cloud instances
  SMB_URL, SMB_USERNAME and SMB_PASSWORD, are expected to be populated
  in your AutoPkg preferences, override Input variables, or by
  command-line keys.
Identifier: com.github.davidbpirie.jamf-upload.Docker
MinimumVersion: 2.3.0
ParentRecipe: com.github.smithjw.pkg.Docker

Input:
  NAME: Docker
  ARCHITECTURE: x86_64
  DOWNLOAD_TYPE: amd64
  JAMF_CATEGORY: Developer Tools
  JAMF_PKG_NAME: '%NAME%'
  JAMF_PKG_INFO: Docker Desktop is secure, out-of-the-box containerization software offering developers and teams a robust, hybrid toolkit to build, share, and run applications anywhere.
  JAMF_PKG_NOTES: 'Generated and uploaded by AutoPkg'
  JAMF_PKG_PRIORITY: '10'
  JAMF_PKG_REBOOT_REQUIRED: 'False'
  JAMF_PKG_OS_REQUIREMENTS: ''
  JAMF_PKG_REQUIRED_PROCESSOR: None
  JAMF_PKG_SEND_NOTIFICATION: 'False'
  JAMF_PKG_REPLACE: 'False'
  JAMF_PKG_REPLACE_METADATA: 'False'

Process:
  - Processor: com.github.grahampugh.jamf-upload.processors/JamfPackageUploader
    Arguments:
      pkg_name: '%JAMF_PKG_NAME%-%version%.pkg'
      pkg_category: '%JAMF_CATEGORY%'
      pkg_info: '%JAMF_PKG_INFO%'
      pkg_notes: '%JAMF_PKG_NOTES%'
      pkg_priority: '%JAMF_PKG_PRIORITY%'
      reboot_required: '%JAMF_PKG_REBOOT_REQUIRED%'
      os_requirements: '%JAMF_PKG_OS_REQUIREMENTS%'
      required_processor: '%JAMF_PKG_REQUIRED_PROCESSOR%'
      send_notification: '%JAMF_PKG_SEND_NOTIFICATION%'
      replace_pkg: '%JAMF_PKG_REPLACE%'
      replace_pkg_metadata: '%JAMF_PKG_REPLACE_METADATA%'

  - Processor: PathDeleter
    Arguments:
      path_list:
      - '%pkg_path%'
